name: simplytranslate
version: 1.2.4
description: Free and unlimited Google translations and TTS. Fast and private.
#author: Marvin Perzi
homepage: https://github.com/Persie0/SimplyTranslate-dart
dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: any

environment:
  sdk: '>=2.15.0 <4.0.0'
