name: simplytranslate
version: 1.2.2
description: Free and unlimited Google translations and TTS. Fast and private.
#author: Marvin Perzi
homepage: https://github.com/Persie0/SimplyTranslate-dart
dependencies:
  http: ^0.13.4
  web_scraper: ^0.1.4

dev_dependencies:
  lints: ^2.0.0
  test: any

environment:
  sdk: ">=2.12.0 <3.0.0"
