name: simplytranslate
version: 2.0.1
description: Free and unlimited Google translations and TTS. Fast and private.
#author: Marvin Perzi
homepage: https://github.com/Persie0/SimplyTranslate-dart
dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: any

environment:
  sdk: '>=2.15.0 <4.0.0'
