name: simplytranslate
version: 1.0.7
description: Free and unlimited Google and Libretranslate translations and Google TTS. Fast and private. Working with the SimplyTranslate API.
#author: Marvin Perzi
homepage: https://github.com/Persie0/SimplyTranslate-dart
dependencies:
  http: ^0.13.4

dev_dependencies:
  test: any

environment:
  sdk: ">=2.12.0 <3.0.0"
